name: ECE 285 CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    container:
      image: sisaha9/ece285_finance_wi23:stable
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Script
        if: ${{ github.event_name == 'pull_request' }}
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          python3 main.py
      - name: Run Script CI
        if: ${{ github.event_name != 'pull_request' }}
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          DISCORD_API_KEY: ${{ secrets.DISCORD_API_KEY }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: |
          python3 main.py --ci
      - name: Upload Run results
        uses: actions/upload-artifact@v3
        with:
          name: run-results
          path: results/
