name: ECE 285 CI

on:
  pull_request:
    branches:
      - master

jobs:
  run-ci:
    runs-on: ubuntu-latest
    container:
      image: sisaha9/ece285_finance_wi23:stable
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python3 portfolio.py
      - uses: actions/upload-artifact@v3
        with:
          name: run-results
          path: results/